id: P000524
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG3712
  title: བློ་སྦྱོང་ལེགས་བཤད་ཀུན་འདུས
  author: ''
  volumes:
    3a2f45bd3fd946dfa5504a4b6e8e73d4:
      image_group_id: I1KG3799
      title: Volume 1 of blo sbyong legs bshad kun 'dus
      volume_number: 1
      total_pages: 252
      base_file: v001.txt
